#i might try looking into tmuxinator
#https://github.com/joshmedeski/sesh/issues/184
#https://github.com/tmuxinator/tmuxinator

dir_length = 2

[default_session]
startup_command = "l"
preview_command = "eza --all --git --icons --color=always {}"
# preview_command = "l"
#
# [default_session]
# startup_command = "nvim -c ':Telescope find_files'"
# preview_command = "eza --all --git --icons --color=always {}"

[[session]]
name = "code"
path = "~/Code"

# [[session]]
# name = "DOom emacs config Óò≤ "
# path = "~/.nix/dump/.doom.d/"

[[session]]
name = "neovim"
path = "~/.nix/dump/.config/nvim"
startup_command = "git status"

# [[session]]
# name = "POrtage config üß¥"
# path = "~/.pumpfiles/root/etc/portage/"

[[session]]
name = "nix"
# name = "nix Û±ÑÖ"
path = "~/.nix"
startup_command = "git status"

[[session]]
name = "scripts"
path = "~/.nix/dump/.scripts"

[[session]]
name = "sesh"
path = "~/.nix/dump/.config/sesh"
startup_command = "$EDITOR sesh.toml"
preview_command = "cat sesh.toml"

[[session]]
name = "ssh"
startup_command = "ssh gravity@clr"
preview_command = "ping clr -c 1"

[[session]]
name = "tmux"
path = "~/.nix/dump"
startup_command = "$EDITOR .tmux.conf"
preview_command = "cat .tmux.conf"

# [[session]]
# name = "Little cool website" 
# path = "~/Code/coollittlewebsite"
# startup_command = "~/.config/sesh/scripts/coollittlewebsite.sh"

[[session]]
name = "notes" 
path = "~/Notes"
startup_command = "nvim index.md +'Obsidian today'"

# [[session]]
# name = "TOmato üçÖ" 
# startup_command = "exec tomato"
