#i might try looking into tmuxinator
#https://github.com/joshmedeski/sesh/issues/184
#https://github.com/tmuxinator/tmuxinator

[default_session]
startup_command = "l"
preview_command = "eza --all --git --icons --color=always {}"
# preview_command = "l"
#
# [default_session]
# startup_command = "nvim -c ':Telescope find_files'"
# preview_command = "eza --all --git --icons --color=always {}"

# [[session]]
# name = "COde üíª"
# path = "~/Code"

# [[session]]
# name = "DOom emacs config Óò≤ "
# path = "~/.nix/home/dump/.doom.d/"

[[session]]
name = "neovim"
path = "~/.nix/home/dump/.config/nvim"
startup_command = "git status"

# [[session]]
# name = "POrtage config üß¥"
# path = "~/.pumpfiles/root/etc/portage/"

[[session]]
name = "nix"
# name = "nix Û±ÑÖ"
path = "~/.nix"

[[session]]
name = "scripts"
path = "~/.nix/home/dump/.scripts"

[[session]]
name = "sesh"
path = "~/.nix/home/dump/.config/sesh"
startup_command = "$editor sesh.toml"
preview_command = "cat sesh.toml"

[[session]]
name = "ssh"
startup_command = "exec ssh gravity@clr"

[[session]]
name = "tmux"
path = "~/.nix/home/dump"
startup_command = "$EDITOR .tmux.conf"
preview_command = "cat .tmux.conf"

[[session]]
name = "Little cool website" 
path = "~/Code/coollittlewebsite"
startup_command = "~/.config/sesh/scripts/coollittlewebsite.sh"

# [[session]]
# name = "TOmato üçÖ" 
# startup_command = "exec tomato"
