[default_session]
startup_command = "l"
# preview_command = "l"
#
# [default_session]
# startup_command = "nvim -c ':Telescope find_files'"
# preview_command = "eza --all --git --icons --color=always {}"

[[session]]
name = "COde ğŸ’»"
path = "~/Code"

[[session]]
name = "DOom emacs config î˜² "
path = "~/.nix/home/dump/.doom.d/"

[[session]]
name = "NEovim config ï¯ "
path = "~/.nix/home/dump/.config/nvim"
startup_command = "git status"

[[session]]
name = "POrtage config ğŸ§´"
path = "~/.pumpfiles/root/etc/portage/"

[[session]]
name = "NIx ó±„…"
path = "~/.nix"
startup_command = "git status"

[[session]]
name = "SCripts ğŸ“œ "
path = "~/.nix/home/dump/.scripts"

[[session]]
name = "SEsh config îµ” "
path = "~/.nix/home/dump/.config/sesh"
startup_command = "$EDITOR sesh.toml"

[[session]]
name = "SSh ó°£€ "
startup_command = "ssh gravity@clr"

[[session]]
name = "TMux config î¯ˆ "
startup_command = "$EDITOR ~/.nix/home/dump/.tmux.conf"

[[session]]
name = "LIttle cool website" 
path = "~/Code/coollittlewebsite"
startup_command = "~/.config/sesh/scripts/coollittlewebsite.sh"

[[session]]
name = "TOmato ğŸ…" 
startup_command = "tomato"
